### ISSUE TITLE
`parse` return type not consistent

### ISSUE THREAD

**Issue by samialsheikh** [iw4p/partialjson#2]
https://github.com/iw4p/partialjson/blob/main/partialjson/json_parser.py#L27-L38

In the success case we return `json.loads` (dict) but otherwise `json.dumps` (str). Is this behavior intentional? If not, perhaps they should all be json.loads to make the return type always a dictionary.

**Comment by iw4p** [comment]
Hi, I think you are suggesting:

```
    def parse(self, s):
        if len(s) >= 1:
            try:
                return json.loads(s)
            except json.JSONDecodeError as e:
                data, reminding = self.parse_any(s, e)
                self.last_parse_reminding = reminding
                if self.on_extra_token and reminding:
                    self.on_extra_token(s, data, reminding)
                return json.loads(json.dumps(data))
        else:
            return json.loads({})
```

Is it what you mean?

**Comment by iw4p** [comment]
I updated partialjson.

**Comment by samialsheikh** [comment]
Yes that's what I was getting at! Though I think now that else branch is broken, because of the input type to json.loads being a dict instead of string. To fix, I think you could do `json.loads("{}")`

**Comment by iw4p** [comment]
Fixed! Thank you so much! I hoped you could contribute to this project directly to see your name in contributors.
Still, feel free to modify code and don't forget to update the `__version__ = "0.0.x"` in `__init__.py` file.
